### ISSUE TITLE
how can I set proxy ?

### ISSUE THREAD

**Issue by biandh** [developersdigest/llm-answer-engine#32]
when I run :
npm run dev

I get this info:

> ai-rsc-demo@0.0.0 dev
> next dev

   ▲ Next.js 14.1.2
   - Local:        http://localhost:3000
   - Environments: .env

 ✓ Ready in 1763ms
 ○ Compiling / ...
 ✓ Compiled / in 4.8s (10805 modules)
 ⨯ ReferenceError: window is not defined
    at __webpack_require__ (/Users/xxl/llm-answer-engine/.next/server/edge-runtime-webpack.js:37:33)
    at fn (/Users/xxl/llm-answer-engine/.next/server/edge-runtime-webpack.js:318:21)
    at eval (./components/answer/Map.tsx:10:65)
    at (ssr)/./components/answer/Map.tsx (/Users/xxl/llm-answer-engine/.next/server/app/page.js:188:1)
    at __webpack_require__ (/Users/xxl/llm-answer-engine/.next/server/edge-runtime-webpack.js:37:33)
    at fn (/Users/xxl/llm-answer-engine/.next/server/edge-runtime-webpack.js:318:21)
 ✓ Compiled in 460ms (5070 modules)
Error fetching videos: [Error: Network response was not ok. Status: 403]
Error: Network response was not ok. Status: 403
    at getVideos (webpack-internal:///(rsc)/./app/action.tsx:233:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 2)
    at async eval (webpack-internal:///(rsc)/./app/action.tsx:299:69)
Error: Network response was not ok. Status: 403
    at getVideos (webpack-internal:///(rsc)/./app/action.tsx:233:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 2)
    at async eval (webpack-internal:///(rsc)/./app/action.tsx:299:69)
 ⨯ unhandledRejection: Error: Network response was not ok. Status: 403
    at getVideos (webpack-internal:///(rsc)/./app/action.tsx:233:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 2)
    at async eval (webpack-internal:///(rsc)/./app/action.tsx:299:69)
 ⨯ unhandledRejection: Error: Network response was not ok. Status: 403
    at getVideos (webpack-internal:///(rsc)/./app/action.tsx:233:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 2)
    at async eval (webpack-internal:///(rsc)/./app/action.tsx:299:69)
There was a problem with your fetch operation:  [TypeError: fetch failed] {
  cause:  [ConnectTimeoutError: Connect Timeout Error] {
  name: 'ConnectTimeoutError',
  code: 'UND_ERR_CONNECT_TIMEOUT',
  message: 'Connect Timeout Error'
}
}
Error fetching search results:  [TypeError: fetch failed] {
  cause:  [ConnectTimeoutError: Connect Timeout Error] {
  name: 'ConnectTimeoutError',
  code: 'UND_ERR_CONNECT_TIMEOUT',
  message: 'Connect Timeout Error'
}
}
The streamable UI has been slow to update. This may be a bug or a performance issue or you forgot to call `.done()`.

**Comment by developersdigest** [comment]
This is likely the result of an issue related to the leaflet map component not having a dynamic import. This should now be resolved. Thank you!
