### ISSUE TITLE
UPSTASH_VECTOR_REST_TOKEN is missing Error

### ISSUE THREAD

**Issue by usa3234** [developersdigest/llm-answer-engine#52]
I am encountering an error related to the UPSTASH_VECTOR_REST_TOKEN environment variable when trying to run the server. The error log is as follows:

⨯ Error: UPSTASH_VECTOR_REST_TOKEN is missing!
    at eval (./app/action.tsx:65:19)
    at (rsc)/./app/action.tsx (/data/perplexica/llm-answer-engine/.next/server/app/page.js:4778:1)
    at __webpack_require__ (/data/perplexica/llm-answer-engine/.next/server/edge-runtime-webpack.js:37:33)
    at fn (/data/perplexica/llm-answer-engine/.next/server/edge-runtime-webpack.js:318:21)
    at eval (./app/layout.tsx:14:65)
    at (rsc)/./app/layout.tsx (/data/perplexica/llm-answer-engine/.next/server/app/page.js:4822:1)
    at __webpack_require__ (/data/perplexica/llm-answer-engine/.next/server/edge-runtime-webpack.js:37:33)
    at Function.fn (/data/perplexica/llm-answer-engine/.next/server/edge-runtime-webpack.js:318:21)
 ⨯ Error: UPSTASH_VECTOR_REST_TOKEN is missing!
    at eval (./app/action.tsx:65:19)
    at (rsc)/./app/action.tsx (/data/perplexica/llm-answer-engine/.next/server/app/page.js:4778:1)
    at __webpack_require__ (/data/perplexica/llm-answer-engine/.next/server/edge-runtime-webpack.js:37:33)
    at fn (/data/perplexica/llm-answer-engine/.next/server/edge-runtime-webpack.js:318:21)
    at eval (./app/layout.tsx:14:65)
    at (rsc)/./app/layout.tsx (/data/perplexica/llm-answer-engine/.next/server/app/page.js:4822:1)
    at __webpack_require__ (/data/perplexica/llm-answer-engine/.next/server/edge-runtime-webpack.js:37:33)
    at Function.fn (/data/perplexica/llm-answer-engine/.next/server/edge-runtime-webpack.js:318:21)
digest: "1947390288"
 ⨯ Error: UPSTASH_VECTOR_REST_TOKEN is missing!
    at eval (./app/action.tsx:65:19)
    at (rsc)/./app/action.tsx (/data/perplexica/llm-answer-engine/.next/server/app/page.js:4778:1)
    at __webpack_require__ (/data/perplexica/llm-answer-engine/.next/server/edge-runtime-webpack.js:37:33)
    at fn (/data/perplexica/llm-answer-engine/.next/server/edge-runtime-webpack.js:318:21)
    at eval (./app/layout.tsx:14:65)
    at (rsc)/./app/layout.tsx (/data/perplexica/llm-answer-engine/.next/server/app/page.js:4822:1)
    at __webpack_require__ (/data/perplexica/llm-answer-engine/.next/server/edge-runtime-webpack.js:37:33)
    at Function.fn (/data/perplexica/llm-answer-engine/.next/server/edge-runtime-webpack.js:318:21)
[Error: UPSTASH_VECTOR_REST_TOKEN is missing!] { digest: '552280776' }
 ⨯ [Error: UPSTASH_VECTOR_REST_TOKEN is missing!] { digest: '552280776' }
 ⨯ [TypeError: Cannot read properties of null (reading 'default')]

The server fails to start with the error UPSTASH_VECTOR_REST_TOKEN is missing! despite this token being optional as per the documentation. I only intend to use the following API keys: OPENAI_API_KEY, GROQ_API_KEY, BRAVE_SEARCH_API_KEY, and SERPER_API.

The server should start without requiring UPSTASH_VECTOR_REST_TOKEN since it is optional. please help me.

**Comment by developersdigest** [comment]
Hello, thank you

In the app/config.tsx, ensure the following value is set to false;

useRateLimiting: false

Cheers

**Comment by developersdigest** [comment]
*     useSemanticCache: false 

this value

**Comment by AmoghSaxena** [comment]
I did the same still getting same error 
Changes useSemanticCache: false

Still same error @developersdigest 

```
llm-answer-engine-1  |  ○ Compiling / ...
llm-answer-engine-1  |  ✓ Compiled / in 65.6s (11124 modules)
llm-answer-engine-1  |  ⨯ Error: UPSTASH_VECTOR_REST_TOKEN is missing!
llm-answer-engine-1  |     at eval (./app/tools/semanticCache.tsx:22:19)
llm-answer-engine-1  |     at (rsc)/./app/tools/semanticCache.tsx (/home/node/app/.next/server/app/page.js:5236:1)
llm-answer-engine-1  |     at __webpack_require__ (/home/node/app/.next/server/edge-runtime-webpack.js:37:33)
llm-answer-engine-1  |     at fn (/home/node/app/.next/server/edge-runtime-webpack.js:318:21)
llm-answer-engine-1  |     at eval (./app/action.tsx:13:78)
llm-answer-engine-1  |     at (rsc)/./app/action.tsx (/home/node/app/.next/server/app/page.js:5053:1)
llm-answer-engine-1  |     at __webpack_require__ (/home/node/app/.next/server/edge-runtime-webpack.js:37:33)
llm-answer-engine-1  |     at fn (/home/node/app/.next/server/edge-runtime-webpack.js:318:21)
llm-answer-engine-1  |     at eval (./app/layout.tsx:14:65)
llm-answer-engine-1  |  ⨯ Error: UPSTASH_VECTOR_REST_TOKEN is missing!
llm-answer-engine-1  |     at eval (./app/tools/semanticCache.tsx:22:19)
llm-answer-engine-1  |     at (rsc)/./app/tools/semanticCache.tsx (/home/node/app/.next/server/app/page.js:5236:1)
llm-answer-engine-1  |     at __webpack_require__ (/home/node/app/.next/server/edge-runtime-webpack.js:37:33)
llm-answer-engine-1  |     at fn (/home/node/app/.next/server/edge-runtime-webpack.js:318:21)
llm-answer-engine-1  |     at eval (./app/action.tsx:13:78)
llm-answer-engine-1  |     at (rsc)/./app/action.tsx (/home/node/app/.next/server/app/page.js:5053:1)
llm-answer-engine-1  |     at __webpack_require__ (/home/node/app/.next/server/edge-runtime-webpack.js:37:33)
llm-answer-engine-1  |     at fn (/home/node/app/.next/server/edge-runtime-webpack.js:318:21)
llm-answer-engine-1  |     at eval (./app/layout.tsx:14:65)
llm-answer-engine-1  | digest: "528755030"
llm-answer-engine-1  |  ⨯ Error: UPSTASH_VECTOR_REST_TOKEN is missing!
llm-answer-engine-1  |     at eval (./app/tools/semanticCache.tsx:22:19)
llm-answer-engine-1  |     at (rsc)/./app/tools/semanticCache.tsx (/home/node/app/.next/server/app/page.js:5236:1)
llm-answer-engine-1  |     at __webpack_require__ (/home/node/app/.next/server/edge-runtime-webpack.js:37:33)
llm-answer-engine-1  |     at fn (/home/node/app/.next/server/edge-runtime-webpack.js:318:21)
llm-answer-engine-1  |     at eval (./app/action.tsx:13:78)
llm-answer-engine-1  |     at (rsc)/./app/action.tsx (/home/node/app/.next/server/app/page.js:5053:1)
llm-answer-engine-1  |     at __webpack_require__ (/home/node/app/.next/server/edge-runtime-webpack.js:37:33)
llm-answer-engine-1  |     at fn (/home/node/app/.next/server/edge-runtime-webpack.js:318:21)
llm-answer-engine-1  |     at eval (./app/layout.tsx:14:65)
llm-answer-engine-1  | [Error: UPSTASH_VECTOR_REST_TOKEN is missing!] { digest: '528755030' }
llm-answer-engine-1  |  ⨯ [Error: UPSTASH_VECTOR_REST_TOKEN is missing!] { digest: '528755030' }
llm-answer-engine-1  |  ⨯ [TypeError: Cannot read properties of null (reading 'default')]
llm-answer-engine-1  |  ✓ Compiled in 1992ms (5124 modules)
```
